### ISSUE TITLE
Scproxy sudden stopped working

### ISSUE THREAD

**Issue by CodieMonster** [wvengen/scproxy#4]
Hey,
I have enjoyed your bypass-solution for over two months now. Today it suddenly stopped working. I have tried with differ user-switcher agent to no awail. Scproxy also stopped working on my colleagues computer. Could there be some new update ByPass that stops your script from working?

#TEST1
systemd-socket-activate -l 31505 python3 scproxy.py
Listening on [::]:31505 as 3.
Communication attempt on fd 3.
Execing python3 (python3 scproxy.py)
^CTraceback (most recent call last):
File "/home/user/scproxy/scproxy.py", line 236, in
httpd.handle_request()
File "/usr/lib64/python3.12/socketserver.py", line 297, in handle_request
if selector.select(timeout):
^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib64/python3.12/selectors.py", line 415, in select
fd_event_list = self._selector.poll(timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

#TEST2
curl --insecure -H 'Sec-Fetch-Mode: cors' -H 'Origin: https://secure.buypass.no' \ 
     --data-raw '' https://127.0.0.1:31505/scard/list/
curl: (7) Failed to connect to 127.0.0.1 port 31505 after 0 ms: Couldn't connect to server

**Comment by CodieMonster** [comment]
systemd-socket-activate -l 31505 python3 scproxy.py
Listening on [::]:31505 as 3.
Communication attempt on fd 3.
Execing python3 (python3 scproxy.py)
^CTraceback (most recent call last):
  File "/home/user/scproxy/scproxy.py", line 236, in <module>
    httpd.handle_request()
  File "/usr/lib64/python3.12/socketserver.py", line 297, in handle_request
    if selector.select(timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by wvengen** [comment]
Hi, thanks for your bug report. That is strange, I'm using it successfully. Running the commands you give above, works for me.
Do you have the latest version? I'm seeing slightly different line numbers on Ctrl-C.

**Comment by wvengen** [comment]
```
$ systemd-socket-activate --version
systemd 249 (249.11-0ubuntu3.12)
+PAM +AUDIT +SELINUX +APPARMOR +IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 -PWQUALITY -P11KIT -QRENCODE +BZIP2 +LZ4 +XZ +ZLIB +ZSTD -XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
$ python3 --version
Python 3.10.12
```
